### ISSUE TITLE
Rust should come after Programming Languages ABC

### ISSUE THREAD

**Issue by romanbird** [AbdesamedBendjeddou/Rusty-CS#4]
When you follow this curriculum right now, you have your very first encounter with the following topics in the Rust Book, when you could have had your first encounter with them in Programming Languages ABC.

- Tuples (why tuples? why lists? when to pick?)
- References
- Mutability pros and cons
- Object oriented programming (when to use? pros and cons?)
- Pattern matching
- Closures 
- probably more I'm missing

It will probably also give you a better insight into why you want to actually use Rust (obviously its an exciting language with mad growth right now but the actual features behind it aren't going to just be immediately obvious to anyone). No brainer change for me

**Comment by AbdesamedBendjeddou** [comment]
That's a good point, I wanted to keep the exposure to Rust as early in the curriculum as possible because I thought many newcomers might be excited to try some Rust only to be faced with a course that is known to be challenging and somewhat boring at first, while I do agree with what you suggested, I'm afraid that pushing Rust further by another course may cause some people to jump or skip courses.
I also think that the official book has a decent introduction to some of those topics.
We need to assess the presumed outcomes of each choice (to push Rust further or not) and see which one's benefit outweighs the other

**Comment by romanbird** [comment]
True, maybe a compromise that's not learning the entirety of Rust between the two (ie intro Rust with just a couple chapters) is best of both worlds

**Comment by AbdesamedBendjeddou** [comment]
At what chapter should we put the break? I think chapter 5 would be good. This way will defer the exposure to closers and pattern matching till after PLABC. 
Chapter 12 also seems like a good break point, moving to another course after doing a small Project in Rust
